sudo: false
language: python
cache:
  pip: true
  directories:
  - "$HOME/.cached_models"
python:
- '2.7'
- '3.4'
env:
  matrix:
  - TEST=test/test_exp_survival_model.py
  - TEST=test/test_exp_survival_model_sim.py
  - TEST=test/test_pem_survival_model.py
  - TEST=test/test_pem_survival_model_sim.py
  - TEST=test/test_weibull_survival_model.py
  - TEST=test/test_weibull_survival_model_sim.py
  - TEST=test/test_pem_survival_model_varcoefs.py
  - TEST=test/test_pem_survival_model_varcoefs_sim.py
  - TEST=test/test_pem_survival_model_timevarying.py
  - TEST=test/test_pem_survival_model_timevarying_sim.py
  - TEST=test/test_byo-gamma_survival_model.py
  - TEST=test/test_byo-gamma_survival_model_sim.py
  - TEST=test/test_jointmodel_datasets.py
  - TEST=test/test_formulas.py
  - TEST=test/test_SurvivalStanData.py
before_install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- echo -e "#\x21/bin/bash\n\$@ > wait4.out 2>&1 3>&1 &\nPROCESS=\"\$!\"\nfunction
  finish {\ncat wait4.out\n}\ntrap finish EXIT\nwhile :\ndo\n  RESULT=\`ps -p \${PROCESS}
  -o comm=\`" > wait4.sh
- echo -e "  if [ -z \"\${RESULT}\" ]; then\n    wait \${PROCESS}; exit \$?\n  else\n    echo
  \"-\"; sleep 10\n  fi\ndone\nexit \$?" >> wait4.sh
- more wait4.sh
- chmod 755 wait4.sh
addons:
  apt:
    packages:
    - pandoc
install:
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy nose
  pandas matplotlib
- source activate test-environment
- pip install -r requirements.txt
- pip install -r test_requirements.txt
- pip install .
- pip install coveralls
script:
- "./lint.sh"
- "./wait4.sh nosetests $TEST --with-coverage --cover-package=survivalstan"
after_success: coveralls
deploy:
  provider: pypi
  user: jackinovik
  password:
    secure: bsV2HqaxnHV4TWRRGBQooBuHSXlqZucnHPWDL5dBLrZ18/Jc2eXcDzVfy7lWyOY/yKdkHhQgQGtZPgNUMKxSudmz+QQOyiIfWylPh/pyJ0XNo8CSNpMniB437LfEF3pvUR2AvJOUcdQwPXfWUWmeR3qe5rFfMBYNrGtNdK2FqsRkJTzgRG1yC4yiO5dnR5LunS8Tr61XGgMQCBSVxz/rDdu7/fb7Vs8kPOkatm0rvKGKBxw9kufbXbW4CIIe9nIY12snAnil1PiE9/YYYa64QJhAiLAPuFxnZbby1FPHDPoaU7AzwgCl2vzKI1FY5D54UdDuVwTwgTRHEhIIZdIHiMnejUgzK19Ta17kRu+IxA/BUJRSGxTJV9x+SZPFDPZ9YZcFh8CMSTxpXIMg3TO2A5foMLbBlTFyBxyj3Bb7D9uzCk/GqwFnzi7GH77HS69CC/umexdbsIpEI1FVKDNVHy+bOos1NjFoVBM3+oSxEbppc6sc1g3a5O3GGQPW8ceHlA3soJfaFWnTUOgubncl8DNzzicLMAL1wENkb9YnkI8A+mxVnH0vY1ZoDkXMBBDZl/NqN6IfgPt37ZvXKV7nun+TtlzTQ82byQbBsrO5kBTEnyAzSsqAmAnRK5hsh2j6wtxkb99gxoT+8pYZXuwMkEajrHFG3T+Q+HzzrbXn4Ps=
  on:
    branch: master
    tags: true
  skip_existing: true
